### ISSUE TITLE
white leftBar

### ISSUE THREAD

**Issue by DaRandomCube** [Godiesc/firefox-gx#125]
![image](https://github.com/Godiesc/firefox-gx/assets/93283139/d7038fde-c88a-4b64-9ba1-a55a9ef087ba)
self explanatory, idk what is the reason
os : arch linux
version : 121.0-1
what it working before : yes, i don't remember changing anything

**Comment by Tintouin** [comment]
What is your windows manager ? Can you do a neofetch or something ? I use Arch btw.
Did it change since you've updated your Firefox-GX version for the latest release ? 
Is the font Times New Roman by default, or you did change it ?

LibreWolf is certainly a reason of the problem, this add-on is intended for Firefox, but I'm not sure of that since those are really close to each other.
I can also see that your menu bar has misalignment on the date, it may be the consequence of a dotfile that enter in conflict with whatever you did recently.

@Godiesc should know exactly what to change, but the compatibility on Unix based distros isn't perfect yet, and he can't test it on these so reporting any problem is very useful.

**Comment by Godiesc** [comment]
@DaRandomCube hi, be sure to use a compatible theme, that is a frequent bug when you use the "system theme" or an incompatible theme, try to use one of the themes shared in the main github-page and test if the problem disappear.

![imagen](https://github.com/Godiesc/firefox-gx/assets/22057609/58ecfa4c-3b0a-4832-98c3-679a0e09922d)

**Comment by DaRandomCube** [comment]
thanks, the theme i used was this, you made this so it should be compatible with the lift bar right? turns out it's not
![image](https://github.com/Godiesc/firefox-gx/assets/93283139/3878c544-613c-45e2-9ab8-1bbc0133c871)
