### ISSUE TITLE
Extensions are stuck pinned near the tabs

### ISSUE THREAD

**Issue by SlideShowGames** [Godiesc/firefox-gx#170]
![Screenshot_20240609_110955](https://github.com/Godiesc/firefox-gx/assets/108354503/5df67329-c3e1-41ad-9d88-a9b3f2e722db)

**Comment by Godiesc** [comment]
hi,
I assume you are using the latest version of the theme (downloaded from de 'releases' section) and you are using the release Firefox version, if not pls update the theme or Firefox.
If you are up to date pls share your OS, Firefox version and 'Extras' you are using to test if the problem is persistent in my end.
