### ISSUE TITLE
Can you make Opera one? It has a novel appearance.

### ISSUE THREAD

**Issue by spphinslove** [Godiesc/firefox-gx#54]
![图片](https://user-images.githubusercontent.com/11383988/236115324-ec21dd51-bfdb-44b6-96d9-4ed6418f8c56.png)
https://www.opera.com/one

**Comment by Godiesc** [comment]
hi,
I saw few days ago that new interface but is to much different of the GX style, the tabs seems to be the same than the default Firefox, the "Group tabs" style is something you can't do with CSS so that is impossible, AFAIK.
Make and maintain a new theme takes a lot of time, it's impossible to me, sorry.
