### ISSUE TITLE
Is there any way to get rid of the blur in new tab icons?

### ISSUE THREAD

**Issue by AzureRT456** [Godiesc/firefox-gx#62]
Referencing this:

![image](https://github.com/Godiesc/firefox-gx/assets/128042952/77913408-5d1a-41bd-a4bb-b901e5e72eee)

The search bar also has a blur. If there is any way to remove this blur, that would be nice.

**Comment by Godiesc** [comment]
hi, in the future you should use the [Discussions](https://github.com/Godiesc/firefox-gx/discussions) section to get help to do things like this because is not an issue or bug.

you can delete the blur effect changing the line 54 in the `chrome/components/ogx_root-personal.css` file, like this:

`--personal-blur: blur(0px) ;`
